export const CHANGE_HABIT_NAME = "CHANGE_HABIT_NAME";
export const CHANGE_HABIT_CATEGORY = "CHANGE_HABIT_CATEGORY";
export const CHANGE_HABIT_FREQUENCY = "CHANGE_HABIT_FREQUENCY";
export const CHANGE_HABIT_GOAL = "CHANGE_HABIT_GOAL";
export const CHANGE_HABIT_TIMELINE = "CHANGE_HABIT_TIMELINE";
export const LOAD_HABIT = "LOAD_HABIT";
