export const CHANGE_HABIT_NAME = "CHANGE_HABIT_NAME";
export const CHANGE_HABIT_TYPE = "CHANGE_HABIT_TYPE";
export const CHANGE_HABIT_FREQ = "CHANGE_HABIT_FREQ";
export const CHANGE_HABIT_GOAL = "CHANGE_HABIT_GOAL";
export const CHANGE_HABIT_DURATION = "CHANGE_HABIT_DURATION";
